name: deploy-foo
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    environment: foo
    runs-on: ubuntu-latest
    steps:
      - name: fake-deploy
        run: |
          echo 'fake'
