name: pr-validation
on:
  workflow_dispatch: # allow manual triggering
  pull_request:
    branches: [main]
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      # sleep for 5 seconds to force the second job that targets environmment foo to run shortly after deploy-foo.yml runs
      - shell: pwsh
        run: Start-Sleep -s 5
  build-and-test:
    needs: sleep
    environment: foo
    # TODO: #5 using matrix is failing even though using windows and ubuntu explictly is not. Need to investigate. For now, just testing with ubuntu-latest.
    
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [windows-latest, ubuntu-latest]
    #   fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-action
        uses: ./
        with:
          environment: foo